Auth
antipattern-team/wishlist_backend pull request #1
Opened 2019-08-01 19:35 UTC by UsatiyNyan

2019-08-02 12:15 UTC, AntonyMoes requested changes
Еще мб подумать над именованием auth_server.py и auth_client.py

2019-08-02 12:15 UTC, AntonyMoes commented on docker-compose.yml
> +      AUTHKEY: 'e5Grab2bwfcL6NWjTgEB'
Заливаем секретную информацию в опенсорс :^)

2019-08-02 12:15 UTC, AntonyMoes commented on auth_server/settings/__init__.py
> +sleep = False
Добавил функцию в utils на получение таких переменных

2019-08-02 12:15 UTC, AntonyMoes commented on api/handlers.py
> +async def login(request: web.Request):
В части кода web.Request проставлен, в другой части - нет

2019-08-02 12:15 UTC, AntonyMoes commented on api/handlers.py
> +@auth_mw
пока это не нужно на данном методе

2019-08-02 12:15 UTC, AntonyMoes commented on docker-compose.yml
> +      - 5674:5674
Экспоузить порты не надо, внутри сети они и так видны

2019-08-02 12:15 UTC, AntonyMoes commented on auth_server/auth_server.py
> +    await asyncio.sleep(0.05)
Что за слипы?

2019-08-02 12:15 UTC, AntonyMoes commented on auth_server/auth_server.py
> +    print(f" [.] got({jwt.decode(encoded_token, auth_key, algorithms=['HS256'])})")
Принты надо убрать

2019-08-02 12:15 UTC, AntonyMoes commented on api/middleware.py
> +            if decoded_token == "":  # 0.5) if not valid, just delete it => rewrite the cookie
Если токен не валидный, может, возвращать не пустую строку, а `None`?

2019-08-02 12:15 UTC, AntonyMoes commented on api/server.py
> +        app.auth_connection = await AuthRpcClient().connect(
Как-то выбивается из общей стилизации

2019-08-02 12:15 UTC, AntonyMoes commented on auth_server/settings/__init__.py
> +import os
`auth_server/settings/__init__.py`
А почему `__init__.py`, если он нигде в проекте больше не используется? 
Можно поменять структуру проекта, но хотелось бы понять

2019-08-02 12:15 UTC, AntonyMoes commented on auth_server/Dockerfile
> +ENV SLEEP 1
sleep нужен толко зависящим от эластика сервисам, потому что он оч долго стартует
Или rmq тоже тормозит?

2019-08-02 12:58 UTC, UsatiyNyan commented on auth_server/Dockerfile
> +ENV SLEEP 1
без слипа, происходит то же самое что и с эластиком - rmq не успевает запускаться

2019-08-03 13:56 UTC, AntonyMoes approved these changes

2019-08-03 13:56 UTC, merged

2019-08-03 13:58 UTC, AntonyMoes commented on auth_server/auth_server.py
> +    await asyncio.sleep(0.05)
@UsatiyNyan, и все-таки что это такое?